format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$battery\
$line_break\
$character
"""
[username]
show_always = true
style_user='bright-red bold' 
format = '[$user@]($style)'
[hostname]
ssh_only = false
ssh_symbol='☁️ '
style = '#0A8D45 bold'
format = '[$ssh_symbol$hostname⚽]($style) '
[time]
disabled = false
style = 'bold'
format = '\[[$time]($style)\] '
